TypeError: Type not convertible to expected type.
Type enum ConditionalEscrow.Team is not implicitly convertible to expected type uint8.
        scores[Team.SAN_FRANCISCO_49ERS] > scores[Team.KANSAS_CITY_CHIEFS]