TypeError: uint256 is not implicitly convertible
TypeError: Return argument type uint256 is not implicitly convertible to expected type (type of first return variable) bool.
        return depositsOf(msg.sender);